### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by edisonqu**
Adding a way to set up the API key like this might help anyone get started with using Pestuary.

### CODE REVIEW

**Comment by anjor** [comment]
Is there a reason you prefer this method to setting it as an environment variable? The environment variable way makes it easy to hide an api key.

**Comment by edisonqu** [comment]
Yes, although using `export APIKEY= "(API_KEY)"` may be more secure and makes it easier to hide it, in exchange, it sacrifices the usability and efficiency of the SDK. Some developers with little CLI knowledge might have trouble setting up Pestuary as they might run into problems trying to setup their APIKEY. 

Other SDKs also allow the developers to put the API key inside the file rather than putting it in env, for example the[ pinata API SDK ](https://github.com/Vourhey/pinatapy), 

`python
from pinatapy import PinataPy
pinata = PinataPy(<pinata_api_key>, <pinata_secret_api_key>)`

You can see that the Pinata API key is embedded inside the file rather than through env to make it easier to use for the developers. It is just a suggestion though, I do think a quickstart using of whichever method might help many developers onto Pestuary.

**Comment by anjor** [comment]
Yeah I am not a big fan of this way of using API keys. Definitely prefer it to be an environment variable especially because that makes deployment to hosting services like render or vercel easier.

Would you mind changing the readme to reflect what we currently have (set the APIKEY environment variable) and I will approve the PR.

Thanks for contribution!

**Comment by edisonqu** [comment]
I understand and thank you for your reasoning. I updated the README. Thank you for giving me the opportunity to support Estuary's mission.

I hope to make a bigger impact in the future and will keep an eye out for opportunities to improve Estuary's mission and the SDK.

**Review by anjor — APPROVED** [review]

**Pull request merged**
